/*
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BeezUPCommonLOVLink2;
import io.swagger.client.model.BeezUPCommonListOfValueItem;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LOVApi
 */
@Ignore
public class LOVApiTest {

    private final LOVApi api = new LOVApi();

    
    /**
     * Get all list names
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPublicListNamesTest() throws ApiException {
        List<BeezUPCommonLOVLink2> response = api.getPublicListNames();

        // TODO: test validations
    }
    
    /**
     * Get the list of values related to this list name
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPublicListOfValuesTest() throws ApiException {
        String listName = null;
        List<String> acceptLanguage = null;
        List<BeezUPCommonListOfValueItem> response = api.getPublicListOfValues(listName, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * Get all list names
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserListNamesTest() throws ApiException {
        List<BeezUPCommonLOVLink2> response = api.getUserListNames();

        // TODO: test validations
    }
    
    /**
     * Get the list of values related to this list name
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserListOfValuesTest() throws ApiException {
        String listName = null;
        List<String> acceptLanguage = null;
        List<BeezUPCommonListOfValueItem> response = api.getUserListOfValues(listName, acceptLanguage);

        // TODO: test validations
    }
    
}
