/*
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GetChannelCatalogProductInfoListRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-03T09:59:46.672Z")
public class GetChannelCatalogProductInfoListRequest {
  @SerializedName("sku")
  private String sku = null;

  @SerializedName("title")
  private String title = null;

  public GetChannelCatalogProductInfoListRequest sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * The product sku to search
   * @return sku
  **/
  @ApiModelProperty(example = "null", value = "The product sku to search")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public GetChannelCatalogProductInfoListRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The  product title to search
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "The  product title to search")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetChannelCatalogProductInfoListRequest getChannelCatalogProductInfoListRequest = (GetChannelCatalogProductInfoListRequest) o;
    return Objects.equals(this.sku, getChannelCatalogProductInfoListRequest.sku) &&
        Objects.equals(this.title, getChannelCatalogProductInfoListRequest.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sku, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetChannelCatalogProductInfoListRequest {\n");
    
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

