/*
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BeezUPColumnConfiguration;
import io.swagger.client.model.BeezUPCommonErrorResponseMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CatalogsGlobalApi
 */
@Ignore
public class CatalogsGlobalApiTest {

    private final CatalogsGlobalApi api = new CatalogsGlobalApi();

    
    /**
     * Get the BeezUP columns
     *
     * Get the BeezUP columns, this columns are used for mapping during the manual catalog importation process.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void catalogGetBeezUPColumnsTest() throws ApiException {
        List<BeezUPColumnConfiguration> response = api.catalogGetBeezUPColumns();

        // TODO: test validations
    }
    
}
